[package]
name = "keru_draw"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { version = "27", features = ["spirv"] }
bytemuck = { version = "1.14", features = ["derive"] }
textslabs = { path = "../textslabs" }
keru_svg = { path = "../keru_svg" }

[dev-dependencies]
winit = "0.30"
pollster = "0.4"

[[example]]
name = "example"
path = "examples/example.rs"
